"use client";
import React from "react";
import { SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/navigation";
import styles from "@/styles/Homepage/HomeCarousel.module.scss";
import HomeDetailCard from "./HomeDetailCard";
import Heading from "../Heading";
// import { Navigation } from "swiper/modules";
import { globalServices } from "@/services/global.services";
import { useQuery } from "@tanstack/react-query";
import { HomeData, HomeDataRes } from "@/src/types/propertyCard";
import { Button, Link } from "@nextui-org/react";
import HomeCardSkeleton from "./HomeCardSkeleton";

async function fetchProperties(recent?: boolean) {
  // const res = await globalServices.getAll(`/properties${recent? "/recent" : ""}?limit=8`)
  // if (res.status === 200 && res.data.data) {
  //   const propertyData = res.data.data.length > 0 ? res.data.data.map((data: HomeDataRes) => ({
  //     title: data.CityRegion ?? data.City ?? "",
  //     sqft: data.LivingAreaRange ?? 0,
  //     beds: data.BedroomsTotal ?? 0,
  //     baths: data.BathroomsTotalInteger ?? 0,
  //     images: data.images?.length > 0 ? data.images.map((image: { order: number; image_url: string}) => image.image_url) : [],
  //     address: data.UnparsedAddress,
  //     price: (data.ListPrice ?? 0).toLocaleString("en-US"),
  //     listingKey: data.ListingKey,
  //     transactionType: data.TransactionType ?? "",
  //     isFavorite: data.is_favorite ?? false,
  //   })) : []
  //   return propertyData;
  // } else {
  //   return []
  // }

  let data = [
    {
        "feed_type": "idx",
        "ListingKey": "X11957774",
        "AccessibilityFeatures": [],
        "AccessToProperty": [],
        "AdditionalMonthlyFee": null,
        "AdditionalMonthlyFeeFrequency": null,
        "AlternativePower": [],
        "Amps": null,
        "ApartmentNumber": null,
        "ApproximateAge": null,
        "ArchitecturalStyle": [],
        "AssessmentYear": 2024,
        "AssociationAmenities": [],
        "AssociationFee": null,
        "AssociationFeeIncludes": [],
        "AssociationName": null,
        "AttachedGarageYN": null,
        "BalconyType": null,
        "Basement": [],
        "BasementYN": null,
        "BathroomsTotalInteger": 0,
        "BaySizeLengthFeet": null,
        "BaySizeLengthInches": null,
        "BaySizeWidthFeet": null,
        "BaySizeWidthInches": null,
        "BedroomsAboveGrade": null,
        "BedroomsBelowGrade": null,
        "BedroomsTotal": 0,
        "BoardPropertyType": null,
        "BuildingAreaTotal": null,
        "BuildingAreaUnits": null,
        "BuildingName": null,
        "BusinessName": null,
        "BusinessType": [],
        "CableYNA": true,
        "CentralVacuumYN": false,
        "ChannelName": null,
        "ChattelsYN": null,
        "City": "North Huron",
        "CityRegion": "Blyth",
        "ClearHeightFeet": null,
        "ClearHeightInches": null,
        "CommercialCondoFee": null,
        "CommercialCondoFeeFrequency": null,
        "CommonAreaUpcharge": null,
        "CommunityFeatures": [],
        "CondoCorpNumber": null,
        "ConstructionMaterials": [],
        "ContractStatus": "Available",
        "Cooling": [],
        "CoolingYN": null,
        "Country": "CA",
        "CountyOrParish": "Huron",
        "CoveredSpaces": null,
        "CraneYN": null,
        "CrossStreet": "Hwy 4 going north, pass county road 23 (Blyth Rd) go past Hamiton St. and property on the left hand side.",
        "DDFYN": true,
        "DenFamilyroomYN": null,
        "DevelopmentChargesPaid": [],
        "DirectionFaces": "West",
        "Disclosures": [],
        "DockingType": [],
        "DoubleManShippingDoors": null,
        "DoubleManShippingDoorsHeightFeet": null,
        "DoubleManShippingDoorsHeightInches": null,
        "DoubleManShippingDoorsWidthFeet": null,
        "DoubleManShippingDoorsWidthInches": null,
        "DriveInLevelShippingDoors": null,
        "DriveInLevelShippingDoorsHeightFeet": null,
        "DriveInLevelShippingDoorsHeightInches": null,
        "DriveInLevelShippingDoorsWidthFeet": null,
        "DriveInLevelShippingDoorsWidthInches": null,
        "ElectricExpense": null,
        "ElectricOnPropertyYN": null,
        "ElectricYNA": "Available",
        "ElevatorType": null,
        "ElevatorYN": null,
        "EnsuiteLaundryYN": false,
        "EstimatedInventoryValueAtCost": null,
        "Expenses": null,
        "Exposure": null,
        "ExteriorFeatures": [],
        "FarmType": null,
        "FinancialStatementAvailableYN": null,
        "FireplaceFeatures": [],
        "FireplaceYN": null,
        "FoundationDetails": [],
        "FranchiseYN": null,
        "FreestandingYN": null,
        "FrontageLength": null,
        "Furnished": null,
        "GarageParkingSpaces": null,
        "GarageType": null,
        "GarageYN": null,
        "GradeLevelShippingDoors": null,
        "GradeLevelShippingDoorsHeightFeet": null,
        "GradeLevelShippingDoorsHeightInches": null,
        "GradeLevelShippingDoorsWidthFeet": null,
        "GradeLevelShippingDoorsWidthInches": null,
        "HeatingExpenses": null,
        "HeatingYN": null,
        "HeatSource": null,
        "HeatType": null,
        "HoursDaysOfOperation": [],
        "HoursDaysOfOperationDescription": null,
        "HSTApplication": true,
        "IndustrialArea": null,
        "IndustrialAreaCode": null,
        "InsuranceExpense": null,
        "InteriorFeatures": [
            "None"
        ],
        "InternetAddressDisplayYN": true,
        "InternetEntireListingDisplayYN": true,
        "KitchensAboveGrade": null,
        "KitchensBelowGrade": null,
        "KitchensTotal": 0,
        "LaundryFeatures": [],
        "LeasedTerms": null,
        "LeaseToOwnEquipment": [],
        "LegalStories": null,
        "LinkProperty": null,
        "LinkYN": null,
        "ListOfficeKey": "568201",
        "ListOfficeName": "RE/MAX Reliable Realty Inc",
        "ListPrice": 599900,
        "ListPriceUnit": null,
        "LivingAreaRange": null,
        "Locker": null,
        "LockerLevel": null,
        "LockerNumber": null,
        "LockerUnit": null,
        "LotDepth": 224,
        "LotDimensionsSource": null,
        "LotFeatures": [],
        "LotIrregularities": null,
        "LotShape": "Rectangular",
        "LotSizeRangeAcres": ".50-1.99",
        "LotSizeSource": "GeoWarehouse",
        "LotSizeUnits": "Feet",
        "LotType": null,
        "MaximumRentalMonthsTerm": null,
        "MediaChangeTimestamp": "2025-02-05T17:19:37.000000Z",
        "MediaListingKey": null,
        "MinimumRentalTermMonths": null,
        "MlsStatus": "New",
        "ModificationTimestamp": "2025-02-05T17:19:37.000000Z",
        "NetOperatingIncome": null,
        "NewConstructionYN": null,
        "NumberOfFullTimeEmployees": null,
        "NumberOfKitchens": null,
        "OccupantType": "Vacant",
        "OfficeApartmentArea": null,
        "OfficeApartmentAreaUnit": null,
        "OriginalEntryTimestamp": "2025-02-05T17:19:37.000000Z",
        "OriginatingSystemID": "A00001796",
        "OtherExpense": null,
        "OtherStructures": [],
        "OutOfAreaMunicipality": null,
        "OutsideStorageYN": null,
        "ParcelNumber": "410700261",
        "ParcelOfTiedLand": null,
        "ParkingFeatures": [
            "None"
        ],
        "ParkingLevelUnit1": null,
        "ParkingLevelUnit2": null,
        "ParkingMonthlyCost": null,
        "ParkingSpaces": null,
        "ParkingSpot1": null,
        "ParkingSpot2": null,
        "ParkingTotal": null,
        "PercentBuilding": null,
        "PetsAllowed": [],
        "PhotosChangeTimestamp": "2025-02-05T17:19:37.000000Z",
        "PoolFeatures": [],
        "PossessionDetails": "Immediate",
        "PostalCode": "N0M 1H0",
        "ProfessionalManagementExpense": null,
        "PropertyAttachedYN": null,
        "PropertyFeatures": [
            "Beach",
            "Campground",
            "School",
            "Rec./Commun.Centre"
        ],
        "PropertyManagementCompany": null,
        "PropertySubType": "Vacant Land",
        "PropertyType": "Residential Freehold",
        "PropertyUse": null,
        "PublicRemarks": "Attention investors and developers! Great opportunity for multi-unit building in the charming town of Blyth! Theatre in town close to Lake Huron, quaint community site plan completed along with engineered drawings for a 6-plex town home or build to suit! Options include Row house, multi-unit dwelling, retirement or nursing home, community facility but buyer has to verify with municipality! Buyer to verify with accountant regarding HST.",
        "PublicRemarksExtras": null,
        "Rail": null,
        "RentIncludes": [],
        "RetailArea": null,
        "RetailAreaCode": null,
        "RollNumber": "405056000200710",
        "Roof": [],
        "RoomsAboveGrade": null,
        "RoomsBelowGrade": null,
        "RoomsTotal": null,
        "RoomType": [],
        "RuralUtilities": [],
        "SeatingCapacity": null,
        "SecurityFeatures": [],
        "SeniorCommunityYN": null,
        "Sewer": [
            "Sewer"
        ],
        "Shoreline": [],
        "ShorelineAllowance": null,
        "ShowingRequirements": [
            "Showing System"
        ],
        "SoilTest": null,
        "SpaYN": null,
        "SpecialDesignation": [
            "Unknown"
        ],
        "SquareFootSource": null,
        "StandardStatus": "Active",
        "StateOrProvince": "ON",
        "StreetDirSuffix": null,
        "StreetName": "PTS 1&2 Queen",
        "StreetNumber": "PL 173",
        "StreetSuffix": "Street",
        "StructureType": [],
        "SurveyAvailableYN": null,
        "TaxAnnualAmount": 1143.84,
        "TaxAssessedValue": 55000,
        "TaxType": null,
        "TaxYear": 2024,
        "TimestampSQL": null,
        "Topography": [],
        "TransactionType": "For Sale",
        "TruckLevelShippingDoors": null,
        "TruckLevelShippingDoorsHeightFeet": null,
        "TruckLevelShippingDoorsHeightInches": null,
        "TruckLevelShippingDoorsWidthFeet": null,
        "TruckLevelShippingDoorsWidthInches": null,
        "UFFI": null,
        "UnderContract": [],
        "UnitNumber": null,
        "UnparsedAddress": "PL 173 PTS 1&2 Queen Street, North Huron, ON N0M 1H0",
        "Utilities": [],
        "VacancyAllowance": null,
        "VendorPropertyInfoStatement": false,
        "View": [],
        "VirtualTourURLUnbranded": null,
        "WashroomsType1": null,
        "WashroomsType1Level": null,
        "WashroomsType1Pcs": null,
        "WashroomsType2": null,
        "WashroomsType2Level": null,
        "WashroomsType2Pcs": null,
        "WashroomsType3": null,
        "WashroomsType3Level": null,
        "WashroomsType3Pcs": null,
        "WashroomsType4": null,
        "WashroomsType4Level": null,
        "WashroomsType4Pcs": null,
        "WashroomsType5": null,
        "WashroomsType5Level": null,
        "WashroomsType5Pcs": null,
        "WaterBodyName": null,
        "WaterBodyType": null,
        "WaterDeliveryFeature": [],
        "WaterExpense": null,
        "Waterfront": [
            "None"
        ],
        "WaterfrontAccessory": [],
        "WaterFrontageFt": null,
        "WaterfrontFeatures": [],
        "WaterfrontYN": false,
        "WaterSource": [],
        "WaterView": [],
        "ZoningDesignation": null,
        "updated_at": "2025-02-05T17:25:03.523000Z",
        "created_at": "2025-02-05T17:25:03.523000Z",
        "id": "67a39eef7edb9401930a6f96",
        "is_favorite": false,
        "images": [
            {
                "Order": 1,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/X11957774/thumbnail/e02b6bd3-a461-472d-bcb0-bdb643ee5603-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            },
            {
                "Order": 0,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/X11957774/thumbnail/6f38c639-c740-47cf-a3ef-f18a87a1dd9a-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            }
        ]
    },
    {
        "feed_type": "idx",
        "ListingKey": "C11957773",
        "AccessibilityFeatures": [],
        "AccessToProperty": [],
        "AdditionalMonthlyFee": null,
        "AdditionalMonthlyFeeFrequency": null,
        "AlternativePower": [],
        "Amps": null,
        "ApartmentNumber": null,
        "ApproximateAge": "New",
        "ArchitecturalStyle": [
            "Apartment"
        ],
        "AssessmentYear": null,
        "AssociationAmenities": [
            "Bike Storage",
            "Concierge",
            "Exercise Room",
            "Outdoor Pool",
            "Rooftop Deck/Garden"
        ],
        "AssociationFee": null,
        "AssociationFeeIncludes": [],
        "AssociationName": "TBD",
        "AttachedGarageYN": true,
        "BalconyType": "Open",
        "Basement": [
            "None"
        ],
        "BasementYN": null,
        "BathroomsTotalInteger": 1,
        "BaySizeLengthFeet": null,
        "BaySizeLengthInches": null,
        "BaySizeWidthFeet": null,
        "BaySizeWidthInches": null,
        "BedroomsAboveGrade": 1,
        "BedroomsBelowGrade": null,
        "BedroomsTotal": 1,
        "BoardPropertyType": "Condo",
        "BuildingAreaTotal": null,
        "BuildingAreaUnits": null,
        "BuildingName": null,
        "BusinessName": null,
        "BusinessType": [],
        "CableYNA": null,
        "CentralVacuumYN": false,
        "ChannelName": null,
        "ChattelsYN": null,
        "City": "Toronto",
        "CityRegion": "Waterfront Communities C1",
        "ClearHeightFeet": null,
        "ClearHeightInches": null,
        "CommercialCondoFee": null,
        "CommercialCondoFeeFrequency": null,
        "CommonAreaUpcharge": null,
        "CommunityFeatures": [],
        "CondoCorpNumber": 0,
        "ConstructionMaterials": [
            "Brick"
        ],
        "ContractStatus": "Available",
        "Cooling": [
            "Central Air"
        ],
        "CoolingYN": true,
        "Country": "CA",
        "CountyOrParish": "Toronto",
        "CoveredSpaces": 0,
        "CraneYN": null,
        "CrossStreet": "Richmond St W & Peter St",
        "DDFYN": true,
        "DenFamilyroomYN": false,
        "DevelopmentChargesPaid": [],
        "DirectionFaces": null,
        "Disclosures": [],
        "DockingType": [],
        "DoubleManShippingDoors": null,
        "DoubleManShippingDoorsHeightFeet": null,
        "DoubleManShippingDoorsHeightInches": null,
        "DoubleManShippingDoorsWidthFeet": null,
        "DoubleManShippingDoorsWidthInches": null,
        "DriveInLevelShippingDoors": null,
        "DriveInLevelShippingDoorsHeightFeet": null,
        "DriveInLevelShippingDoorsHeightInches": null,
        "DriveInLevelShippingDoorsWidthFeet": null,
        "DriveInLevelShippingDoorsWidthInches": null,
        "ElectricExpense": null,
        "ElectricOnPropertyYN": null,
        "ElectricYNA": null,
        "ElevatorType": null,
        "ElevatorYN": null,
        "EnsuiteLaundryYN": false,
        "EstimatedInventoryValueAtCost": null,
        "Expenses": null,
        "Exposure": "South East",
        "ExteriorFeatures": [],
        "FarmType": null,
        "FinancialStatementAvailableYN": null,
        "FireplaceFeatures": [],
        "FireplaceYN": false,
        "FoundationDetails": [],
        "FranchiseYN": null,
        "FreestandingYN": null,
        "FrontageLength": null,
        "Furnished": "Unfurnished",
        "GarageParkingSpaces": null,
        "GarageType": "Underground",
        "GarageYN": true,
        "GradeLevelShippingDoors": null,
        "GradeLevelShippingDoorsHeightFeet": null,
        "GradeLevelShippingDoorsHeightInches": null,
        "GradeLevelShippingDoorsWidthFeet": null,
        "GradeLevelShippingDoorsWidthInches": null,
        "HeatingExpenses": null,
        "HeatingYN": true,
        "HeatSource": "Gas",
        "HeatType": "Forced Air",
        "HoursDaysOfOperation": [],
        "HoursDaysOfOperationDescription": null,
        "HSTApplication": false,
        "IndustrialArea": null,
        "IndustrialAreaCode": null,
        "InsuranceExpense": null,
        "InteriorFeatures": [
            "Other"
        ],
        "InternetAddressDisplayYN": true,
        "InternetEntireListingDisplayYN": true,
        "KitchensAboveGrade": 1,
        "KitchensBelowGrade": null,
        "KitchensTotal": 1,
        "LaundryFeatures": [
            "Ensuite"
        ],
        "LeasedTerms": null,
        "LeaseToOwnEquipment": [],
        "LegalStories": "15",
        "LinkProperty": null,
        "LinkYN": null,
        "ListOfficeKey": "228900",
        "ListOfficeName": "MODERN SOLUTION REALTY INC.",
        "ListPrice": 2500,
        "ListPriceUnit": null,
        "LivingAreaRange": "600-699",
        "Locker": "Owned",
        "LockerLevel": "I",
        "LockerNumber": "52",
        "LockerUnit": null,
        "LotDepth": null,
        "LotDimensionsSource": null,
        "LotFeatures": [],
        "LotIrregularities": null,
        "LotShape": null,
        "LotSizeRangeAcres": null,
        "LotSizeSource": null,
        "LotSizeUnits": null,
        "LotType": null,
        "MaximumRentalMonthsTerm": null,
        "MediaChangeTimestamp": "2025-02-05T17:19:36.000000Z",
        "MediaListingKey": null,
        "MinimumRentalTermMonths": null,
        "MlsStatus": "New",
        "ModificationTimestamp": "2025-02-05T17:19:36.000000Z",
        "NetOperatingIncome": null,
        "NewConstructionYN": true,
        "NumberOfFullTimeEmployees": null,
        "NumberOfKitchens": null,
        "OccupantType": "Owner+Tenant",
        "OfficeApartmentArea": null,
        "OfficeApartmentAreaUnit": null,
        "OriginalEntryTimestamp": "2025-02-05T17:19:36.000000Z",
        "OriginatingSystemID": "A00001796",
        "OtherExpense": null,
        "OtherStructures": [],
        "OutOfAreaMunicipality": null,
        "OutsideStorageYN": null,
        "ParcelNumber": null,
        "ParcelOfTiedLand": null,
        "ParkingFeatures": [
            "Underground"
        ],
        "ParkingLevelUnit1": null,
        "ParkingLevelUnit2": null,
        "ParkingMonthlyCost": null,
        "ParkingSpaces": 0,
        "ParkingSpot1": null,
        "ParkingSpot2": null,
        "ParkingTotal": 0,
        "PercentBuilding": null,
        "PetsAllowed": [
            "Restricted"
        ],
        "PhotosChangeTimestamp": "2025-02-05T17:19:36.000000Z",
        "PoolFeatures": [],
        "PossessionDetails": "TBA",
        "PostalCode": "M5V 0M4",
        "ProfessionalManagementExpense": null,
        "PropertyAttachedYN": true,
        "PropertyFeatures": [
            "Arts Centre",
            "Hospital",
            "Other",
            "Park",
            "Public Transit",
            "Rec./Commun.Centre"
        ],
        "PropertyManagementCompany": "Crossbridge Condominium Services 416-593-6558",
        "PropertySubType": "Condo Apartment",
        "PropertyType": "Residential Condo & Other",
        "PropertyUse": null,
        "PublicRemarks": "Brand New Corner Unit, 636 Sqft 1 Bed On A High Floor With 183 Sqft Outdoor Space Over 2 Balconies Looking South And East. Situated In The Heart Of Entertainment District And Steps From King St, Queen St, Grocery/Drug Stores, Lcbo, Variety Of Restaurant/Bars. The Building Also Features A 24 Hr Concierge, Gym, Party Rooms, Lounge/Dining Room, Games Room, Rooftop Terrace, Outdoor Pool, Bbq Station, Bike Storage.",
        "PublicRemarksExtras": null,
        "Rail": null,
        "RentIncludes": [
            "Building Insurance",
            "Common Elements",
            "Central Air Conditioning",
            "Heat"
        ],
        "RetailArea": null,
        "RetailAreaCode": null,
        "RollNumber": null,
        "Roof": [],
        "RoomsAboveGrade": 4,
        "RoomsBelowGrade": null,
        "RoomsTotal": 4,
        "RoomType": [],
        "RuralUtilities": [],
        "SeatingCapacity": null,
        "SecurityFeatures": [],
        "SeniorCommunityYN": false,
        "Sewer": [],
        "Shoreline": [],
        "ShorelineAllowance": null,
        "ShowingRequirements": [
            "Lockbox"
        ],
        "SoilTest": null,
        "SpaYN": null,
        "SpecialDesignation": [
            "Other",
            "Unknown"
        ],
        "SquareFootSource": "MPAC",
        "StandardStatus": "Active",
        "StateOrProvince": "ON",
        "StreetDirSuffix": "W",
        "StreetName": "Richmond",
        "StreetNumber": "330",
        "StreetSuffix": "Street",
        "StructureType": [],
        "SurveyAvailableYN": null,
        "TaxAnnualAmount": null,
        "TaxAssessedValue": null,
        "TaxType": null,
        "TaxYear": null,
        "TimestampSQL": null,
        "Topography": [],
        "TransactionType": "For Lease",
        "TruckLevelShippingDoors": null,
        "TruckLevelShippingDoorsHeightFeet": null,
        "TruckLevelShippingDoorsHeightInches": null,
        "TruckLevelShippingDoorsWidthFeet": null,
        "TruckLevelShippingDoorsWidthInches": null,
        "UFFI": true,
        "UnderContract": [],
        "UnitNumber": "1515",
        "UnparsedAddress": "#1515 - 330 Richmond Street, Toronto, ON M5V 0M4",
        "Utilities": [],
        "VacancyAllowance": null,
        "VendorPropertyInfoStatement": false,
        "View": [],
        "VirtualTourURLUnbranded": null,
        "WashroomsType1": 1,
        "WashroomsType1Level": null,
        "WashroomsType1Pcs": 3,
        "WashroomsType2": null,
        "WashroomsType2Level": null,
        "WashroomsType2Pcs": null,
        "WashroomsType3": null,
        "WashroomsType3Level": null,
        "WashroomsType3Pcs": null,
        "WashroomsType4": null,
        "WashroomsType4Level": null,
        "WashroomsType4Pcs": null,
        "WashroomsType5": null,
        "WashroomsType5Level": null,
        "WashroomsType5Pcs": null,
        "WaterBodyName": null,
        "WaterBodyType": null,
        "WaterDeliveryFeature": [],
        "WaterExpense": null,
        "Waterfront": [],
        "WaterfrontAccessory": [],
        "WaterFrontageFt": null,
        "WaterfrontFeatures": [],
        "WaterfrontYN": false,
        "WaterSource": [],
        "WaterView": [],
        "ZoningDesignation": null,
        "updated_at": "2025-02-05T17:25:03.488000Z",
        "created_at": "2025-02-05T17:25:03.488000Z",
        "id": "67a39eef7edb9401930a6f95",
        "is_favorite": false,
        "images": [
            {
                "Order": 0,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/C11957773/thumbnail/ba416013-7ff9-4a32-bd3b-0a303ab17073-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            }
        ]
    },
    {
        "feed_type": "idx",
        "ListingKey": "W11957772",
        "AccessibilityFeatures": [],
        "AccessToProperty": [],
        "AdditionalMonthlyFee": null,
        "AdditionalMonthlyFeeFrequency": null,
        "AlternativePower": [],
        "Amps": null,
        "ApartmentNumber": null,
        "ApproximateAge": "16-30",
        "ArchitecturalStyle": [
            "2-Storey"
        ],
        "AssessmentYear": null,
        "AssociationAmenities": [],
        "AssociationFee": null,
        "AssociationFeeIncludes": [],
        "AssociationName": null,
        "AttachedGarageYN": true,
        "BalconyType": null,
        "Basement": [
            "Separate Entrance",
            "Apartment"
        ],
        "BasementYN": null,
        "BathroomsTotalInteger": 4,
        "BaySizeLengthFeet": null,
        "BaySizeLengthInches": null,
        "BaySizeWidthFeet": null,
        "BaySizeWidthInches": null,
        "BedroomsAboveGrade": 4,
        "BedroomsBelowGrade": 2,
        "BedroomsTotal": 6,
        "BoardPropertyType": "Free",
        "BuildingAreaTotal": null,
        "BuildingAreaUnits": null,
        "BuildingName": null,
        "BusinessName": null,
        "BusinessType": [],
        "CableYNA": null,
        "CentralVacuumYN": false,
        "ChannelName": null,
        "ChattelsYN": null,
        "City": "Brampton",
        "CityRegion": "Sandringham-Wellington",
        "ClearHeightFeet": null,
        "ClearHeightInches": null,
        "CommercialCondoFee": null,
        "CommercialCondoFeeFrequency": null,
        "CommonAreaUpcharge": null,
        "CommunityFeatures": [],
        "CondoCorpNumber": null,
        "ConstructionMaterials": [
            "Brick"
        ],
        "ContractStatus": "Available",
        "Cooling": [
            "Central Air"
        ],
        "CoolingYN": true,
        "Country": "CA",
        "CountyOrParish": "Peel",
        "CoveredSpaces": 2,
        "CraneYN": null,
        "CrossStreet": "Torbram Rd & Australia Dr",
        "DDFYN": true,
        "DenFamilyroomYN": true,
        "DevelopmentChargesPaid": [
            "No"
        ],
        "DirectionFaces": "East",
        "Disclosures": [],
        "DockingType": [],
        "DoubleManShippingDoors": null,
        "DoubleManShippingDoorsHeightFeet": null,
        "DoubleManShippingDoorsHeightInches": null,
        "DoubleManShippingDoorsWidthFeet": null,
        "DoubleManShippingDoorsWidthInches": null,
        "DriveInLevelShippingDoors": null,
        "DriveInLevelShippingDoorsHeightFeet": null,
        "DriveInLevelShippingDoorsHeightInches": null,
        "DriveInLevelShippingDoorsWidthFeet": null,
        "DriveInLevelShippingDoorsWidthInches": null,
        "ElectricExpense": null,
        "ElectricOnPropertyYN": null,
        "ElectricYNA": null,
        "ElevatorType": null,
        "ElevatorYN": null,
        "EnsuiteLaundryYN": false,
        "EstimatedInventoryValueAtCost": null,
        "Expenses": null,
        "Exposure": null,
        "ExteriorFeatures": [],
        "FarmType": null,
        "FinancialStatementAvailableYN": null,
        "FireplaceFeatures": [
            "Natural Gas",
            "Family Room"
        ],
        "FireplaceYN": true,
        "FoundationDetails": [
            "Poured Concrete"
        ],
        "FranchiseYN": null,
        "FreestandingYN": null,
        "FrontageLength": null,
        "Furnished": null,
        "GarageParkingSpaces": null,
        "GarageType": "Built-In",
        "GarageYN": true,
        "GradeLevelShippingDoors": null,
        "GradeLevelShippingDoorsHeightFeet": null,
        "GradeLevelShippingDoorsHeightInches": null,
        "GradeLevelShippingDoorsWidthFeet": null,
        "GradeLevelShippingDoorsWidthInches": null,
        "HeatingExpenses": null,
        "HeatingYN": true,
        "HeatSource": "Gas",
        "HeatType": "Forced Air",
        "HoursDaysOfOperation": [],
        "HoursDaysOfOperationDescription": null,
        "HSTApplication": true,
        "IndustrialArea": null,
        "IndustrialAreaCode": null,
        "InsuranceExpense": null,
        "InteriorFeatures": [
            "Carpet Free"
        ],
        "InternetAddressDisplayYN": true,
        "InternetEntireListingDisplayYN": true,
        "KitchensAboveGrade": 1,
        "KitchensBelowGrade": 1,
        "KitchensTotal": 2,
        "LaundryFeatures": [],
        "LeasedTerms": null,
        "LeaseToOwnEquipment": [
            "None"
        ],
        "LegalStories": null,
        "LinkProperty": null,
        "LinkYN": false,
        "ListOfficeKey": "158500",
        "ListOfficeName": "IPRO REALTY LTD.",
        "ListPrice": 1329900,
        "ListPriceUnit": null,
        "LivingAreaRange": null,
        "Locker": null,
        "LockerLevel": null,
        "LockerNumber": null,
        "LockerUnit": null,
        "LotDepth": 85.3,
        "LotDimensionsSource": null,
        "LotFeatures": [],
        "LotIrregularities": null,
        "LotShape": "Rectangular",
        "LotSizeRangeAcres": "< .50",
        "LotSizeSource": "GeoWarehouse",
        "LotSizeUnits": "Feet",
        "LotType": null,
        "MaximumRentalMonthsTerm": null,
        "MediaChangeTimestamp": "2025-02-05T17:18:27.000000Z",
        "MediaListingKey": null,
        "MinimumRentalTermMonths": null,
        "MlsStatus": "New",
        "ModificationTimestamp": "2025-02-05T17:18:27.000000Z",
        "NetOperatingIncome": null,
        "NewConstructionYN": null,
        "NumberOfFullTimeEmployees": null,
        "NumberOfKitchens": null,
        "OccupantType": "Owner+Tenant",
        "OfficeApartmentArea": null,
        "OfficeApartmentAreaUnit": null,
        "OriginalEntryTimestamp": "2025-02-05T17:18:27.000000Z",
        "OriginatingSystemID": "A00001796",
        "OtherExpense": null,
        "OtherStructures": [],
        "OutOfAreaMunicipality": null,
        "OutsideStorageYN": null,
        "ParcelNumber": null,
        "ParcelOfTiedLand": "No",
        "ParkingFeatures": [
            "Private"
        ],
        "ParkingLevelUnit1": null,
        "ParkingLevelUnit2": null,
        "ParkingMonthlyCost": null,
        "ParkingSpaces": 4,
        "ParkingSpot1": null,
        "ParkingSpot2": null,
        "ParkingTotal": 6,
        "PercentBuilding": null,
        "PetsAllowed": [],
        "PhotosChangeTimestamp": "2025-02-05T17:18:27.000000Z",
        "PoolFeatures": [
            "None"
        ],
        "PossessionDetails": null,
        "PostalCode": "L6R 3E8",
        "ProfessionalManagementExpense": null,
        "PropertyAttachedYN": null,
        "PropertyFeatures": [
            "Place Of Worship",
            "Public Transit",
            "School",
            "Hospital",
            "Library"
        ],
        "PropertyManagementCompany": null,
        "PropertySubType": "Detached",
        "PropertyType": "Residential Freehold",
        "PropertyUse": null,
        "PublicRemarks": "Original Aspen Ridge Home, original owner, 4 Bedroom Detached with a 2 bedroom finished basement with separate entrance and kitchen. 2 sets of washer and dryer. No carpet in the home. Hardwood floors on the main and second floor with oak staircase. Laminate flooring in the basement. Roof changed recently (2022), A/C changed recently (2022). California Shutters throughout. Crown molding in the main floor. Entry from the garage to the home. Led pot lights in the main floor. Gas fireplace in the family room. Separate entrance into the basement apartment from the backyard with covered staircase. Kitchen boasts a eat in kitchen area with exit to the backyard. Water heater owned.",
        "PublicRemarksExtras": null,
        "Rail": null,
        "RentIncludes": [],
        "RetailArea": null,
        "RetailAreaCode": null,
        "RollNumber": null,
        "Roof": [
            "Asphalt Shingle"
        ],
        "RoomsAboveGrade": 9,
        "RoomsBelowGrade": null,
        "RoomsTotal": 9,
        "RoomType": [],
        "RuralUtilities": [],
        "SeatingCapacity": null,
        "SecurityFeatures": [
            "Smoke Detector"
        ],
        "SeniorCommunityYN": false,
        "Sewer": [
            "Sewer"
        ],
        "Shoreline": [],
        "ShorelineAllowance": null,
        "ShowingRequirements": [
            "Lockbox"
        ],
        "SoilTest": null,
        "SpaYN": null,
        "SpecialDesignation": [
            "Unknown"
        ],
        "SquareFootSource": null,
        "StandardStatus": "Active",
        "StateOrProvince": "ON",
        "StreetDirSuffix": null,
        "StreetName": "Citronella",
        "StreetNumber": "19",
        "StreetSuffix": "Lane",
        "StructureType": [],
        "SurveyAvailableYN": null,
        "TaxAnnualAmount": 6585.76,
        "TaxAssessedValue": null,
        "TaxType": null,
        "TaxYear": 2024,
        "TimestampSQL": null,
        "Topography": [],
        "TransactionType": "For Sale",
        "TruckLevelShippingDoors": null,
        "TruckLevelShippingDoorsHeightFeet": null,
        "TruckLevelShippingDoorsHeightInches": null,
        "TruckLevelShippingDoorsWidthFeet": null,
        "TruckLevelShippingDoorsWidthInches": null,
        "UFFI": true,
        "UnderContract": [],
        "UnitNumber": null,
        "UnparsedAddress": "19 Citronella Lane, Brampton, ON L6R 3E8",
        "Utilities": [],
        "VacancyAllowance": null,
        "VendorPropertyInfoStatement": false,
        "View": [],
        "VirtualTourURLUnbranded": "https://unbranded.mediatours.ca/property/19-citronella-lane-brampton/",
        "WashroomsType1": 1,
        "WashroomsType1Level": "Ground",
        "WashroomsType1Pcs": 2,
        "WashroomsType2": 1,
        "WashroomsType2Level": "Second",
        "WashroomsType2Pcs": 5,
        "WashroomsType3": 1,
        "WashroomsType3Level": "Second",
        "WashroomsType3Pcs": 4,
        "WashroomsType4": 1,
        "WashroomsType4Level": "Basement",
        "WashroomsType4Pcs": 4,
        "WashroomsType5": null,
        "WashroomsType5Level": null,
        "WashroomsType5Pcs": null,
        "WaterBodyName": null,
        "WaterBodyType": null,
        "WaterDeliveryFeature": [],
        "WaterExpense": null,
        "Waterfront": [],
        "WaterfrontAccessory": [],
        "WaterFrontageFt": null,
        "WaterfrontFeatures": [],
        "WaterfrontYN": false,
        "WaterSource": [],
        "WaterView": [],
        "ZoningDesignation": null,
        "updated_at": "2025-02-05T17:25:03.409000Z",
        "created_at": "2025-02-05T17:25:03.409000Z",
        "id": "67a39eef7edb9401930a6f93",
        "is_favorite": false,
        "images": [
            {
                "Order": 12,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/W11957772/thumbnail/92c408ee-45c4-4480-8574-8936613e4883-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            },
            {
                "Order": 18,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/W11957772/thumbnail/6e8e439e-ab43-4230-92b1-6cf5d42bd4fe-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            }
        ]
    },
    {
        "feed_type": "idx",
        "ListingKey": "N11957771",
        "AccessibilityFeatures": [],
        "AccessToProperty": [],
        "AdditionalMonthlyFee": null,
        "AdditionalMonthlyFeeFrequency": null,
        "AlternativePower": [],
        "Amps": null,
        "ApartmentNumber": null,
        "ApproximateAge": "New",
        "ArchitecturalStyle": [
            "2-Storey"
        ],
        "AssessmentYear": null,
        "AssociationAmenities": [],
        "AssociationFee": null,
        "AssociationFeeIncludes": [],
        "AssociationName": null,
        "AttachedGarageYN": null,
        "BalconyType": null,
        "Basement": [
            "None"
        ],
        "BasementYN": null,
        "BathroomsTotalInteger": 5,
        "BaySizeLengthFeet": null,
        "BaySizeLengthInches": null,
        "BaySizeWidthFeet": null,
        "BaySizeWidthInches": null,
        "BedroomsAboveGrade": 4,
        "BedroomsBelowGrade": null,
        "BedroomsTotal": 4,
        "BoardPropertyType": null,
        "BuildingAreaTotal": null,
        "BuildingAreaUnits": null,
        "BuildingName": null,
        "BusinessName": null,
        "BusinessType": [],
        "CableYNA": null,
        "CentralVacuumYN": false,
        "ChannelName": null,
        "ChattelsYN": null,
        "City": "Bradford West Gwillimbury",
        "CityRegion": "Bond Head",
        "ClearHeightFeet": null,
        "ClearHeightInches": null,
        "CommercialCondoFee": null,
        "CommercialCondoFeeFrequency": null,
        "CommonAreaUpcharge": null,
        "CommunityFeatures": [],
        "CondoCorpNumber": null,
        "ConstructionMaterials": [
            "Brick"
        ],
        "ContractStatus": "Available",
        "Cooling": [
            "Other"
        ],
        "CoolingYN": null,
        "Country": "CA",
        "CountyOrParish": "Simcoe",
        "CoveredSpaces": 2,
        "CraneYN": null,
        "CrossStreet": "Hwy 27 / Simcoe County Rd 88",
        "DDFYN": true,
        "DenFamilyroomYN": true,
        "DevelopmentChargesPaid": [],
        "DirectionFaces": "West",
        "Disclosures": [],
        "DockingType": [],
        "DoubleManShippingDoors": null,
        "DoubleManShippingDoorsHeightFeet": null,
        "DoubleManShippingDoorsHeightInches": null,
        "DoubleManShippingDoorsWidthFeet": null,
        "DoubleManShippingDoorsWidthInches": null,
        "DriveInLevelShippingDoors": null,
        "DriveInLevelShippingDoorsHeightFeet": null,
        "DriveInLevelShippingDoorsHeightInches": null,
        "DriveInLevelShippingDoorsWidthFeet": null,
        "DriveInLevelShippingDoorsWidthInches": null,
        "ElectricExpense": null,
        "ElectricOnPropertyYN": null,
        "ElectricYNA": null,
        "ElevatorType": null,
        "ElevatorYN": false,
        "EnsuiteLaundryYN": false,
        "EstimatedInventoryValueAtCost": null,
        "Expenses": null,
        "Exposure": null,
        "ExteriorFeatures": [],
        "FarmType": null,
        "FinancialStatementAvailableYN": null,
        "FireplaceFeatures": [
            "Natural Gas"
        ],
        "FireplaceYN": true,
        "FoundationDetails": [
            "Concrete"
        ],
        "FranchiseYN": null,
        "FreestandingYN": null,
        "FrontageLength": null,
        "Furnished": null,
        "GarageParkingSpaces": null,
        "GarageType": "Attached",
        "GarageYN": true,
        "GradeLevelShippingDoors": null,
        "GradeLevelShippingDoorsHeightFeet": null,
        "GradeLevelShippingDoorsHeightInches": null,
        "GradeLevelShippingDoorsWidthFeet": null,
        "GradeLevelShippingDoorsWidthInches": null,
        "HeatingExpenses": null,
        "HeatingYN": null,
        "HeatSource": "Gas",
        "HeatType": "Forced Air",
        "HoursDaysOfOperation": [],
        "HoursDaysOfOperationDescription": null,
        "HSTApplication": true,
        "IndustrialArea": null,
        "IndustrialAreaCode": null,
        "InsuranceExpense": null,
        "InteriorFeatures": [
            "Carpet Free"
        ],
        "InternetAddressDisplayYN": true,
        "InternetEntireListingDisplayYN": true,
        "KitchensAboveGrade": 1,
        "KitchensBelowGrade": null,
        "KitchensTotal": 1,
        "LaundryFeatures": [],
        "LeasedTerms": null,
        "LeaseToOwnEquipment": [],
        "LegalStories": null,
        "LinkProperty": null,
        "LinkYN": false,
        "ListOfficeKey": "062203",
        "ListOfficeName": "RIGHT AT HOME REALTY",
        "ListPrice": 1549000,
        "ListPriceUnit": null,
        "LivingAreaRange": "3500-5000",
        "Locker": null,
        "LockerLevel": null,
        "LockerNumber": null,
        "LockerUnit": null,
        "LotDepth": 102,
        "LotDimensionsSource": null,
        "LotFeatures": [],
        "LotIrregularities": null,
        "LotShape": null,
        "LotSizeRangeAcres": null,
        "LotSizeSource": null,
        "LotSizeUnits": "Feet",
        "LotType": null,
        "MaximumRentalMonthsTerm": null,
        "MediaChangeTimestamp": "2025-02-05T17:18:15.000000Z",
        "MediaListingKey": null,
        "MinimumRentalTermMonths": null,
        "MlsStatus": "New",
        "ModificationTimestamp": "2025-02-05T17:18:15.000000Z",
        "NetOperatingIncome": null,
        "NewConstructionYN": null,
        "NumberOfFullTimeEmployees": null,
        "NumberOfKitchens": null,
        "OccupantType": "Vacant",
        "OfficeApartmentArea": null,
        "OfficeApartmentAreaUnit": null,
        "OriginalEntryTimestamp": "2025-02-05T17:18:15.000000Z",
        "OriginatingSystemID": "A00001796",
        "OtherExpense": null,
        "OtherStructures": [],
        "OutOfAreaMunicipality": null,
        "OutsideStorageYN": null,
        "ParcelNumber": null,
        "ParcelOfTiedLand": null,
        "ParkingFeatures": [
            "Private Double"
        ],
        "ParkingLevelUnit1": null,
        "ParkingLevelUnit2": null,
        "ParkingMonthlyCost": null,
        "ParkingSpaces": 4,
        "ParkingSpot1": null,
        "ParkingSpot2": null,
        "ParkingTotal": 6,
        "PercentBuilding": null,
        "PetsAllowed": [],
        "PhotosChangeTimestamp": "2025-02-05T17:18:15.000000Z",
        "PoolFeatures": [
            "None"
        ],
        "PossessionDetails": "TBD",
        "PostalCode": "L0G 1W0",
        "ProfessionalManagementExpense": null,
        "PropertyAttachedYN": null,
        "PropertyFeatures": [
            "Golf",
            "Greenbelt/Conservation"
        ],
        "PropertyManagementCompany": null,
        "PropertySubType": "Detached",
        "PropertyType": "Residential Freehold",
        "PropertyUse": null,
        "PublicRemarks": "Welcome To This Exceptional 4 Bedroom, 5 Bathroom Corner Lot Home. Offering A Generous 3500 Square Feet, It Features Separate Living, Dining, And Family Rooms. Every Bedroom Enjoys Its Own Attached Bathroom. Numerous Upgrades, Including A Stunning White Kitchen With Shaker Cabinets, Upgraded Quartz Countertops, Upgraded Tiles And Upgraded Hardwood Flooring Throughout. Additionally, Enjoy The Luxury Of Glass Showers In Three Of The Bathrooms. Long Driveway With No Sidewalk. 9 Ft Ceiling On The Main Floor And Basement. With A Spacious 44-Foot Lot, Conveniently Located Near Golf Course And Highway.",
        "PublicRemarksExtras": null,
        "Rail": null,
        "RentIncludes": [],
        "RetailArea": null,
        "RetailAreaCode": null,
        "RollNumber": null,
        "Roof": [
            "Shingles"
        ],
        "RoomsAboveGrade": 8,
        "RoomsBelowGrade": null,
        "RoomsTotal": null,
        "RoomType": [],
        "RuralUtilities": [],
        "SeatingCapacity": null,
        "SecurityFeatures": [],
        "SeniorCommunityYN": null,
        "Sewer": [
            "Sewer"
        ],
        "Shoreline": [],
        "ShorelineAllowance": null,
        "ShowingRequirements": [
            "Lockbox"
        ],
        "SoilTest": null,
        "SpaYN": null,
        "SpecialDesignation": [
            "Unknown"
        ],
        "SquareFootSource": null,
        "StandardStatus": "Active",
        "StateOrProvince": "ON",
        "StreetDirSuffix": null,
        "StreetName": "Settlers",
        "StreetNumber": "126",
        "StreetSuffix": "Crescent",
        "StructureType": [],
        "SurveyAvailableYN": null,
        "TaxAnnualAmount": 0,
        "TaxAssessedValue": null,
        "TaxType": null,
        "TaxYear": 2024,
        "TimestampSQL": null,
        "Topography": [],
        "TransactionType": "For Sale",
        "TruckLevelShippingDoors": null,
        "TruckLevelShippingDoorsHeightFeet": null,
        "TruckLevelShippingDoorsHeightInches": null,
        "TruckLevelShippingDoorsWidthFeet": null,
        "TruckLevelShippingDoorsWidthInches": null,
        "UFFI": null,
        "UnderContract": [],
        "UnitNumber": null,
        "UnparsedAddress": "126 Settlers Crescent, Bradford West Gwillimbury, ON L0G 1W0",
        "Utilities": [],
        "VacancyAllowance": null,
        "VendorPropertyInfoStatement": false,
        "View": [],
        "VirtualTourURLUnbranded": "https://youtu.be/R1jr2GujI1w?si=7ssJnXktT0Em8xTh",
        "WashroomsType1": 1,
        "WashroomsType1Level": "Second",
        "WashroomsType1Pcs": 5,
        "WashroomsType2": 1,
        "WashroomsType2Level": "Second",
        "WashroomsType2Pcs": 3,
        "WashroomsType3": 1,
        "WashroomsType3Level": "Second",
        "WashroomsType3Pcs": 3,
        "WashroomsType4": 1,
        "WashroomsType4Level": "Second",
        "WashroomsType4Pcs": 3,
        "WashroomsType5": 1,
        "WashroomsType5Level": "Main",
        "WashroomsType5Pcs": 2,
        "WaterBodyName": null,
        "WaterBodyType": null,
        "WaterDeliveryFeature": [],
        "WaterExpense": null,
        "Waterfront": [],
        "WaterfrontAccessory": [],
        "WaterFrontageFt": null,
        "WaterfrontFeatures": [],
        "WaterfrontYN": false,
        "WaterSource": [],
        "WaterView": [],
        "ZoningDesignation": null,
        "updated_at": "2025-02-05T17:25:03.459000Z",
        "created_at": "2025-02-05T17:25:03.459000Z",
        "id": "67a39eef7edb9401930a6f94",
        "is_favorite": false,
        "images": [
            {
                "Order": 13,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/N11957771/thumbnail/e9308c06-0b22-4c6e-9996-07ca21063d5e-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            },
            {
                "Order": 26,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/N11957771/thumbnail/b6675ff8-9f07-4396-95c3-c5e63a946b42-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            },
            {
                "Order": 23,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/N11957771/thumbnail/e2027471-0052-4340-b015-cc4bc4d30f82-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            },
            {
                "Order": 29,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/N11957771/thumbnail/b2ea6694-2c42-45fc-bd16-6e2964a3cff0-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            }
        ]
    },
    {
        "feed_type": "vow",
        "ListingKey": "X11957770",
        "AccessibilityFeatures": [],
        "AccessToProperty": [],
        "AdditionalMonthlyFee": null,
        "AdditionalMonthlyFeeFrequency": null,
        "AlternativePower": [],
        "Amps": null,
        "ApartmentNumber": null,
        "ApproximateAge": null,
        "ArchitecturalStyle": [],
        "AssessmentYear": null,
        "AssociationAmenities": [],
        "AssociationFee": null,
        "AssociationFeeIncludes": [],
        "AssociationName": null,
        "AttachedGarageYN": null,
        "BalconyType": null,
        "Basement": [],
        "BasementYN": false,
        "BathroomsTotalInteger": null,
        "BaySizeLengthFeet": null,
        "BaySizeLengthInches": null,
        "BaySizeWidthFeet": null,
        "BaySizeWidthInches": null,
        "BedroomsAboveGrade": null,
        "BedroomsBelowGrade": null,
        "BedroomsTotal": null,
        "BoardPropertyType": null,
        "BuildingAreaTotal": 9991,
        "BuildingAreaUnits": "Sq Ft Divisible",
        "BuildingName": null,
        "BusinessName": null,
        "BusinessType": [
            "Retail Store Related"
        ],
        "CableYNA": null,
        "CentralVacuumYN": null,
        "ChannelName": null,
        "ChattelsYN": null,
        "City": "Welland",
        "CityRegion": "768 - Welland Downtown",
        "ClearHeightFeet": 14,
        "ClearHeightInches": null,
        "CommercialCondoFee": null,
        "CommercialCondoFeeFrequency": null,
        "CommonAreaUpcharge": null,
        "CommunityFeatures": [],
        "CondoCorpNumber": null,
        "ConstructionMaterials": [],
        "ContractStatus": "Available",
        "Cooling": [
            "Yes"
        ],
        "CoolingYN": null,
        "Country": "CA",
        "CountyOrParish": "Niagara",
        "CoveredSpaces": null,
        "CraneYN": null,
        "CrossStreet": "Immediately West of HWY 406 and the East Main Street Tunnel",
        "DDFYN": true,
        "DenFamilyroomYN": null,
        "DevelopmentChargesPaid": [],
        "DirectionFaces": null,
        "Disclosures": [],
        "DockingType": [],
        "DoubleManShippingDoors": null,
        "DoubleManShippingDoorsHeightFeet": null,
        "DoubleManShippingDoorsHeightInches": null,
        "DoubleManShippingDoorsWidthFeet": null,
        "DoubleManShippingDoorsWidthInches": null,
        "DriveInLevelShippingDoors": null,
        "DriveInLevelShippingDoorsHeightFeet": null,
        "DriveInLevelShippingDoorsHeightInches": null,
        "DriveInLevelShippingDoorsWidthFeet": null,
        "DriveInLevelShippingDoorsWidthInches": null,
        "ElectricExpense": null,
        "ElectricOnPropertyYN": null,
        "ElectricYNA": null,
        "ElevatorType": "None",
        "ElevatorYN": null,
        "EnsuiteLaundryYN": null,
        "EstimatedInventoryValueAtCost": null,
        "Expenses": null,
        "Exposure": null,
        "ExteriorFeatures": [],
        "FarmType": null,
        "FinancialStatementAvailableYN": null,
        "FireplaceFeatures": [],
        "FireplaceYN": null,
        "FoundationDetails": [],
        "FranchiseYN": null,
        "FreestandingYN": true,
        "FrontageLength": null,
        "Furnished": null,
        "GarageParkingSpaces": null,
        "GarageType": "Outside/Surface",
        "GarageYN": null,
        "GradeLevelShippingDoors": null,
        "GradeLevelShippingDoorsHeightFeet": null,
        "GradeLevelShippingDoorsHeightInches": null,
        "GradeLevelShippingDoorsWidthFeet": null,
        "GradeLevelShippingDoorsWidthInches": null,
        "HeatingExpenses": null,
        "HeatingYN": null,
        "HeatSource": null,
        "HeatType": "Gas Forced Air Open",
        "HoursDaysOfOperation": [],
        "HoursDaysOfOperationDescription": null,
        "HSTApplication": false,
        "IndustrialArea": null,
        "IndustrialAreaCode": null,
        "InsuranceExpense": null,
        "InteriorFeatures": [],
        "InternetAddressDisplayYN": true,
        "InternetEntireListingDisplayYN": true,
        "KitchensAboveGrade": null,
        "KitchensBelowGrade": null,
        "KitchensTotal": null,
        "LaundryFeatures": [],
        "LeasedTerms": null,
        "LeaseToOwnEquipment": [],
        "LegalStories": null,
        "LinkProperty": null,
        "LinkYN": null,
        "ListOfficeKey": null,
        "ListOfficeName": "AVISON YOUNG COMMERCIAL REAL ESTATE SERVICES",
        "ListPrice": 25,
        "ListPriceUnit": "Net Lease",
        "LivingAreaRange": null,
        "Locker": null,
        "LockerLevel": null,
        "LockerNumber": null,
        "LockerUnit": null,
        "LotDepth": 1006,
        "LotDimensionsSource": null,
        "LotFeatures": [],
        "LotIrregularities": null,
        "LotShape": "Rectangular",
        "LotSizeRangeAcres": null,
        "LotSizeSource": null,
        "LotSizeUnits": "Feet",
        "LotType": "Lot",
        "MaximumRentalMonthsTerm": 120,
        "MediaChangeTimestamp": "2025-02-05T17:18:06.000000Z",
        "MediaListingKey": null,
        "MinimumRentalTermMonths": 60,
        "MlsStatus": "New",
        "ModificationTimestamp": "2025-02-05T17:18:06.000000Z",
        "NetOperatingIncome": null,
        "NewConstructionYN": null,
        "NumberOfFullTimeEmployees": null,
        "NumberOfKitchens": null,
        "OccupantType": "Tenant",
        "OfficeApartmentArea": null,
        "OfficeApartmentAreaUnit": null,
        "OriginalEntryTimestamp": "2025-02-05T17:18:06.000000Z",
        "OriginatingSystemID": "A00001796",
        "OtherExpense": null,
        "OtherStructures": [],
        "OutOfAreaMunicipality": null,
        "OutsideStorageYN": null,
        "ParcelNumber": "641160063",
        "ParcelOfTiedLand": null,
        "ParkingFeatures": [],
        "ParkingLevelUnit1": null,
        "ParkingLevelUnit2": null,
        "ParkingMonthlyCost": null,
        "ParkingSpaces": null,
        "ParkingSpot1": null,
        "ParkingSpot2": null,
        "ParkingTotal": null,
        "PercentBuilding": null,
        "PetsAllowed": [],
        "PhotosChangeTimestamp": "2025-02-05T17:18:06.000000Z",
        "PoolFeatures": [],
        "PossessionDetails": "Negotiable",
        "PostalCode": "L3B 3Y9",
        "ProfessionalManagementExpense": null,
        "PropertyAttachedYN": null,
        "PropertyFeatures": [],
        "PropertyManagementCompany": null,
        "PropertySubType": "Commercial Retail",
        "PropertyType": "Commercial",
        "PropertyUse": "Retail",
        "PublicRemarks": "New redevelopment of retail commercial Power Centre on East Main Street in Welland. Directly off of HWY 406 and the East Main Street tunnel with some of the highest traffic counts in the region. Many commercial uses permitted including: Grocery, Commercial Recreation, Retail, Restaurants, Personal Services, Office, Automotive and more. New housing in the immediate area will continue to add density and exposure. Good ceiling heights and natural light. **INTERBOARD LISTING: CORNERSTONE - WATERLOO REGION**",
        "PublicRemarksExtras": null,
        "Rail": "No",
        "RentIncludes": [],
        "RetailArea": 9991,
        "RetailAreaCode": "Sq Ft",
        "RollNumber": "271904000312000",
        "Roof": [],
        "RoomsAboveGrade": null,
        "RoomsBelowGrade": null,
        "RoomsTotal": null,
        "RoomType": [],
        "RuralUtilities": [],
        "SeatingCapacity": null,
        "SecurityFeatures": [
            "Yes"
        ],
        "SeniorCommunityYN": null,
        "Sewer": [
            "Sanitary+Storm"
        ],
        "Shoreline": [],
        "ShorelineAllowance": null,
        "ShowingRequirements": [
            "List Brokerage"
        ],
        "SoilTest": null,
        "SpaYN": null,
        "SpecialDesignation": [],
        "SquareFootSource": null,
        "StandardStatus": "Active",
        "StateOrProvince": "ON",
        "StreetDirSuffix": null,
        "StreetName": "East Main",
        "StreetNumber": "980",
        "StreetSuffix": "Street",
        "StructureType": [],
        "SurveyAvailableYN": null,
        "TaxAnnualAmount": 10,
        "TaxAssessedValue": null,
        "TaxType": "TMI",
        "TaxYear": 2025,
        "TimestampSQL": null,
        "Topography": [],
        "TransactionType": "For Lease",
        "TruckLevelShippingDoors": null,
        "TruckLevelShippingDoorsHeightFeet": null,
        "TruckLevelShippingDoorsHeightInches": null,
        "TruckLevelShippingDoorsWidthFeet": null,
        "TruckLevelShippingDoorsWidthInches": null,
        "UFFI": null,
        "UnderContract": [],
        "UnitNumber": "5",
        "UnparsedAddress": "#5 - 980 East Main Street, Welland, ON L3B 3Y9",
        "Utilities": [
            "Yes"
        ],
        "VacancyAllowance": null,
        "VendorPropertyInfoStatement": false,
        "View": [],
        "VirtualTourURLUnbranded": null,
        "WashroomsType1": null,
        "WashroomsType1Level": null,
        "WashroomsType1Pcs": null,
        "WashroomsType2": null,
        "WashroomsType2Level": null,
        "WashroomsType2Pcs": null,
        "WashroomsType3": null,
        "WashroomsType3Level": null,
        "WashroomsType3Pcs": null,
        "WashroomsType4": null,
        "WashroomsType4Level": null,
        "WashroomsType4Pcs": null,
        "WashroomsType5": null,
        "WashroomsType5Level": null,
        "WashroomsType5Pcs": null,
        "WaterBodyName": null,
        "WaterBodyType": null,
        "WaterDeliveryFeature": [],
        "WaterExpense": null,
        "Waterfront": [],
        "WaterfrontAccessory": [],
        "WaterFrontageFt": null,
        "WaterfrontFeatures": [],
        "WaterfrontYN": null,
        "WaterSource": [],
        "WaterView": [],
        "ZoningDesignation": null,
        "updated_at": "2025-02-05T17:25:04.362000Z",
        "created_at": "2025-02-05T17:25:04.362000Z",
        "id": "67a39ef07edb9401930a6f9e",
        "is_favorite": false,
        "images": [
            {
                "Order": 7,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/X11957770/thumbnail/bcec08e4-d398-417f-b2ce-a1dc1479462e-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            },
            {
                "Order": 0,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/X11957770/thumbnail/906c0c3e-01d7-4146-9967-25c54466eb92-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            },
            {
                "Order": 1,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/X11957770/thumbnail/a67e9767-bf81-4743-9421-0e2f89af4bc9-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            },
            {
                "Order": 2,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/X11957770/thumbnail/bc205d7d-25a9-4bec-bc38-f4d0d76fe9e2-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            }
        ]
    },
    {
        "feed_type": "idx",
        "ListingKey": "N11957767",
        "AccessibilityFeatures": [],
        "AccessToProperty": [],
        "AdditionalMonthlyFee": null,
        "AdditionalMonthlyFeeFrequency": null,
        "AlternativePower": [],
        "Amps": null,
        "ApartmentNumber": null,
        "ApproximateAge": null,
        "ArchitecturalStyle": [],
        "AssessmentYear": null,
        "AssociationAmenities": [],
        "AssociationFee": null,
        "AssociationFeeIncludes": [],
        "AssociationName": null,
        "AttachedGarageYN": null,
        "BalconyType": null,
        "Basement": [],
        "BasementYN": false,
        "BathroomsTotalInteger": null,
        "BaySizeLengthFeet": null,
        "BaySizeLengthInches": null,
        "BaySizeWidthFeet": null,
        "BaySizeWidthInches": null,
        "BedroomsAboveGrade": null,
        "BedroomsBelowGrade": null,
        "BedroomsTotal": null,
        "BoardPropertyType": null,
        "BuildingAreaTotal": 972,
        "BuildingAreaUnits": "Square Feet",
        "BuildingName": null,
        "BusinessName": null,
        "BusinessType": [
            "Other"
        ],
        "CableYNA": null,
        "CentralVacuumYN": null,
        "ChannelName": null,
        "ChattelsYN": null,
        "City": "Vaughan",
        "CityRegion": "Crestwood-Springfarm-Yorkhill",
        "ClearHeightFeet": null,
        "ClearHeightInches": null,
        "CommercialCondoFee": null,
        "CommercialCondoFeeFrequency": null,
        "CommonAreaUpcharge": null,
        "CommunityFeatures": [],
        "CondoCorpNumber": null,
        "ConstructionMaterials": [],
        "ContractStatus": "Available",
        "Cooling": [
            "Yes"
        ],
        "CoolingYN": null,
        "Country": null,
        "CountyOrParish": "York",
        "CoveredSpaces": null,
        "CraneYN": null,
        "CrossStreet": "Yonge / Clark",
        "DDFYN": true,
        "DenFamilyroomYN": null,
        "DevelopmentChargesPaid": [],
        "DirectionFaces": null,
        "Disclosures": [],
        "DockingType": [],
        "DoubleManShippingDoors": null,
        "DoubleManShippingDoorsHeightFeet": null,
        "DoubleManShippingDoorsHeightInches": null,
        "DoubleManShippingDoorsWidthFeet": null,
        "DoubleManShippingDoorsWidthInches": null,
        "DriveInLevelShippingDoors": null,
        "DriveInLevelShippingDoorsHeightFeet": null,
        "DriveInLevelShippingDoorsHeightInches": null,
        "DriveInLevelShippingDoorsWidthFeet": null,
        "DriveInLevelShippingDoorsWidthInches": null,
        "ElectricExpense": null,
        "ElectricOnPropertyYN": null,
        "ElectricYNA": null,
        "ElevatorType": "Public",
        "ElevatorYN": null,
        "EnsuiteLaundryYN": null,
        "EstimatedInventoryValueAtCost": null,
        "Expenses": null,
        "Exposure": null,
        "ExteriorFeatures": [],
        "FarmType": null,
        "FinancialStatementAvailableYN": null,
        "FireplaceFeatures": [],
        "FireplaceYN": null,
        "FoundationDetails": [],
        "FranchiseYN": null,
        "FreestandingYN": false,
        "FrontageLength": null,
        "Furnished": null,
        "GarageParkingSpaces": null,
        "GarageType": "Plaza",
        "GarageYN": null,
        "GradeLevelShippingDoors": null,
        "GradeLevelShippingDoorsHeightFeet": null,
        "GradeLevelShippingDoorsHeightInches": null,
        "GradeLevelShippingDoorsWidthFeet": null,
        "GradeLevelShippingDoorsWidthInches": null,
        "HeatingExpenses": null,
        "HeatingYN": null,
        "HeatSource": null,
        "HeatType": "Gas Forced Air Open",
        "HoursDaysOfOperation": [],
        "HoursDaysOfOperationDescription": null,
        "HSTApplication": false,
        "IndustrialArea": null,
        "IndustrialAreaCode": null,
        "InsuranceExpense": null,
        "InteriorFeatures": [],
        "InternetAddressDisplayYN": true,
        "InternetEntireListingDisplayYN": true,
        "KitchensAboveGrade": null,
        "KitchensBelowGrade": null,
        "KitchensTotal": null,
        "LaundryFeatures": [],
        "LeasedTerms": null,
        "LeaseToOwnEquipment": [],
        "LegalStories": null,
        "LinkProperty": null,
        "LinkYN": null,
        "ListOfficeKey": "043900",
        "ListOfficeName": "RE/MAX PREMIER INC.",
        "ListPrice": 20,
        "ListPriceUnit": "Sq Ft Net",
        "LivingAreaRange": null,
        "Locker": null,
        "LockerLevel": null,
        "LockerNumber": null,
        "LockerUnit": null,
        "LotDepth": 0,
        "LotDimensionsSource": null,
        "LotFeatures": [],
        "LotIrregularities": null,
        "LotShape": null,
        "LotSizeRangeAcres": null,
        "LotSizeSource": null,
        "LotSizeUnits": "Feet",
        "LotType": "Unit",
        "MaximumRentalMonthsTerm": 60,
        "MediaChangeTimestamp": "2025-02-05T17:17:20.000000Z",
        "MediaListingKey": null,
        "MinimumRentalTermMonths": 36,
        "MlsStatus": "New",
        "ModificationTimestamp": "2025-02-05T17:17:20.000000Z",
        "NetOperatingIncome": null,
        "NewConstructionYN": null,
        "NumberOfFullTimeEmployees": null,
        "NumberOfKitchens": null,
        "OccupantType": "Vacant",
        "OfficeApartmentArea": 972,
        "OfficeApartmentAreaUnit": "Sq Ft",
        "OriginalEntryTimestamp": "2025-02-05T17:17:20.000000Z",
        "OriginatingSystemID": "A00001796",
        "OtherExpense": null,
        "OtherStructures": [],
        "OutOfAreaMunicipality": null,
        "OutsideStorageYN": null,
        "ParcelNumber": null,
        "ParcelOfTiedLand": null,
        "ParkingFeatures": [],
        "ParkingLevelUnit1": null,
        "ParkingLevelUnit2": null,
        "ParkingMonthlyCost": null,
        "ParkingSpaces": null,
        "ParkingSpot1": null,
        "ParkingSpot2": null,
        "ParkingTotal": null,
        "PercentBuilding": null,
        "PetsAllowed": [],
        "PhotosChangeTimestamp": "2025-02-05T17:17:20.000000Z",
        "PoolFeatures": [],
        "PossessionDetails": "Immediate/TBA",
        "PostalCode": "L4J 7Y7",
        "ProfessionalManagementExpense": null,
        "PropertyAttachedYN": null,
        "PropertyFeatures": [],
        "PropertyManagementCompany": null,
        "PropertySubType": "Office",
        "PropertyType": "Commercial",
        "PropertyUse": "Office",
        "PublicRemarks": "Prime 2nd-floor medical and professional space with elevator access * Former doctor's office * Functional, spacious layout * Built out with 3 examination rooms with wash sinks, 1 private office, inviting reception area, and convenient ensuite bathroom * Landlord will consider a wide range of medical and related uses, personal service use, office and other professional use * This site is strategically located at a signalized intersection with prominent exposure on the southwest corner of Yonge and Clark * Busy plaza with tenants such as Diagnostic Imaging Lab (ultrasound, x-ray, mammography, bone density, blood lab) Obstetrician, Dental, Pharmacy, Sushi Restaurant, Turkish Restaurant, Bubble Tea, Stitch Master, Print Club, Hair Salon & Spa, Century 21 and more.  Established trade area surrounded with mixed-use of high-density residential, office, retail and industrial * High pedestrian and vehicular traffic * Multiple ingress and egress from 2 surrounding streets.",
        "PublicRemarksExtras": null,
        "Rail": null,
        "RentIncludes": [],
        "RetailArea": null,
        "RetailAreaCode": null,
        "RollNumber": null,
        "Roof": [],
        "RoomsAboveGrade": null,
        "RoomsBelowGrade": null,
        "RoomsTotal": null,
        "RoomType": [],
        "RuralUtilities": [],
        "SeatingCapacity": null,
        "SecurityFeatures": [
            "Yes"
        ],
        "SeniorCommunityYN": null,
        "Sewer": [
            "Sanitary+Storm"
        ],
        "Shoreline": [],
        "ShorelineAllowance": null,
        "ShowingRequirements": [
            "See Brokerage Remarks",
            "Showing System",
            "List Salesperson"
        ],
        "SoilTest": null,
        "SpaYN": null,
        "SpecialDesignation": [],
        "SquareFootSource": null,
        "StandardStatus": "Active",
        "StateOrProvince": "ON",
        "StreetDirSuffix": null,
        "StreetName": "Yonge",
        "StreetNumber": "7330",
        "StreetSuffix": "Street",
        "StructureType": [],
        "SurveyAvailableYN": null,
        "TaxAnnualAmount": 20,
        "TaxAssessedValue": null,
        "TaxType": "T&O",
        "TaxYear": 2024,
        "TimestampSQL": null,
        "Topography": [],
        "TransactionType": "For Lease",
        "TruckLevelShippingDoors": null,
        "TruckLevelShippingDoorsHeightFeet": null,
        "TruckLevelShippingDoorsHeightInches": null,
        "TruckLevelShippingDoorsWidthFeet": null,
        "TruckLevelShippingDoorsWidthInches": null,
        "UFFI": null,
        "UnderContract": [],
        "UnitNumber": "218",
        "UnparsedAddress": "#218 - 7330 Yonge Street, Vaughan, ON L4J 7Y7",
        "Utilities": [
            "Available"
        ],
        "VacancyAllowance": null,
        "VendorPropertyInfoStatement": false,
        "View": [],
        "VirtualTourURLUnbranded": null,
        "WashroomsType1": null,
        "WashroomsType1Level": null,
        "WashroomsType1Pcs": null,
        "WashroomsType2": null,
        "WashroomsType2Level": null,
        "WashroomsType2Pcs": null,
        "WashroomsType3": null,
        "WashroomsType3Level": null,
        "WashroomsType3Pcs": null,
        "WashroomsType4": null,
        "WashroomsType4Level": null,
        "WashroomsType4Pcs": null,
        "WashroomsType5": null,
        "WashroomsType5Level": null,
        "WashroomsType5Pcs": null,
        "WaterBodyName": null,
        "WaterBodyType": null,
        "WaterDeliveryFeature": [],
        "WaterExpense": null,
        "Waterfront": [],
        "WaterfrontAccessory": [],
        "WaterFrontageFt": null,
        "WaterfrontFeatures": [],
        "WaterfrontYN": null,
        "WaterSource": [],
        "WaterView": [],
        "ZoningDesignation": null,
        "updated_at": "2025-02-05T17:20:04.833000Z",
        "created_at": "2025-02-05T17:20:04.833000Z",
        "id": "67a39dc47daf956a910ba8ba",
        "is_favorite": false,
        "images": [
            {
                "Order": 7,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/N11957767/thumbnail/e65b79c8-054d-458c-b96d-e0b85cfada9d-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            },
            {
                "Order": 11,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/N11957767/thumbnail/d26edf19-afd8-4b73-b400-4094cb679d68-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            }
        ]
    },
    {
        "feed_type": "idx",
        "ListingKey": "C11957766",
        "AccessibilityFeatures": [],
        "AccessToProperty": [],
        "AdditionalMonthlyFee": null,
        "AdditionalMonthlyFeeFrequency": null,
        "AlternativePower": [],
        "Amps": null,
        "ApartmentNumber": null,
        "ApproximateAge": null,
        "ArchitecturalStyle": [
            "Loft"
        ],
        "AssessmentYear": null,
        "AssociationAmenities": [
            "BBQs Allowed",
            "Bike Storage",
            "Concierge",
            "Gym",
            "Rooftop Deck/Garden",
            "Visitor Parking"
        ],
        "AssociationFee": null,
        "AssociationFeeIncludes": [],
        "AssociationName": "TSCC",
        "AttachedGarageYN": true,
        "BalconyType": "Terrace",
        "Basement": [
            "None"
        ],
        "BasementYN": null,
        "BathroomsTotalInteger": 2,
        "BaySizeLengthFeet": null,
        "BaySizeLengthInches": null,
        "BaySizeWidthFeet": null,
        "BaySizeWidthInches": null,
        "BedroomsAboveGrade": 2,
        "BedroomsBelowGrade": null,
        "BedroomsTotal": 2,
        "BoardPropertyType": "Condo",
        "BuildingAreaTotal": null,
        "BuildingAreaUnits": null,
        "BuildingName": "Six50 King Lofts",
        "BusinessName": null,
        "BusinessType": [],
        "CableYNA": null,
        "CentralVacuumYN": false,
        "ChannelName": null,
        "ChattelsYN": null,
        "City": "Toronto",
        "CityRegion": "Waterfront Communities C1",
        "ClearHeightFeet": null,
        "ClearHeightInches": null,
        "CommercialCondoFee": null,
        "CommercialCondoFeeFrequency": null,
        "CommonAreaUpcharge": null,
        "CommunityFeatures": [],
        "CondoCorpNumber": 2066,
        "ConstructionMaterials": [
            "Concrete"
        ],
        "ContractStatus": "Available",
        "Cooling": [
            "Central Air"
        ],
        "CoolingYN": true,
        "Country": "CA",
        "CountyOrParish": "Toronto",
        "CoveredSpaces": 1,
        "CraneYN": null,
        "CrossStreet": "King & Bathurst",
        "DDFYN": true,
        "DenFamilyroomYN": true,
        "DevelopmentChargesPaid": [],
        "DirectionFaces": null,
        "Disclosures": [],
        "DockingType": [],
        "DoubleManShippingDoors": null,
        "DoubleManShippingDoorsHeightFeet": null,
        "DoubleManShippingDoorsHeightInches": null,
        "DoubleManShippingDoorsWidthFeet": null,
        "DoubleManShippingDoorsWidthInches": null,
        "DriveInLevelShippingDoors": null,
        "DriveInLevelShippingDoorsHeightFeet": null,
        "DriveInLevelShippingDoorsHeightInches": null,
        "DriveInLevelShippingDoorsWidthFeet": null,
        "DriveInLevelShippingDoorsWidthInches": null,
        "ElectricExpense": null,
        "ElectricOnPropertyYN": null,
        "ElectricYNA": null,
        "ElevatorType": null,
        "ElevatorYN": true,
        "EnsuiteLaundryYN": false,
        "EstimatedInventoryValueAtCost": null,
        "Expenses": null,
        "Exposure": "West",
        "ExteriorFeatures": [],
        "FarmType": null,
        "FinancialStatementAvailableYN": null,
        "FireplaceFeatures": [],
        "FireplaceYN": false,
        "FoundationDetails": [],
        "FranchiseYN": null,
        "FreestandingYN": null,
        "FrontageLength": null,
        "Furnished": "Furnished",
        "GarageParkingSpaces": null,
        "GarageType": "Underground",
        "GarageYN": true,
        "GradeLevelShippingDoors": null,
        "GradeLevelShippingDoorsHeightFeet": null,
        "GradeLevelShippingDoorsHeightInches": null,
        "GradeLevelShippingDoorsWidthFeet": null,
        "GradeLevelShippingDoorsWidthInches": null,
        "HeatingExpenses": null,
        "HeatingYN": true,
        "HeatSource": "Gas",
        "HeatType": "Forced Air",
        "HoursDaysOfOperation": [],
        "HoursDaysOfOperationDescription": null,
        "HSTApplication": false,
        "IndustrialArea": null,
        "IndustrialAreaCode": null,
        "InsuranceExpense": null,
        "InteriorFeatures": [
            "Auto Garage Door Remote",
            "Carpet Free"
        ],
        "InternetAddressDisplayYN": true,
        "InternetEntireListingDisplayYN": true,
        "KitchensAboveGrade": 1,
        "KitchensBelowGrade": null,
        "KitchensTotal": 1,
        "LaundryFeatures": [
            "Ensuite"
        ],
        "LeasedTerms": null,
        "LeaseToOwnEquipment": [],
        "LegalStories": "4",
        "LinkProperty": null,
        "LinkYN": null,
        "ListOfficeKey": "062220",
        "ListOfficeName": "RIGHT AT HOME REALTY",
        "ListPrice": 4300,
        "ListPriceUnit": null,
        "LivingAreaRange": "1000-1199",
        "Locker": "None",
        "LockerLevel": null,
        "LockerNumber": null,
        "LockerUnit": null,
        "LotDepth": null,
        "LotDimensionsSource": null,
        "LotFeatures": [],
        "LotIrregularities": null,
        "LotShape": null,
        "LotSizeRangeAcres": null,
        "LotSizeSource": null,
        "LotSizeUnits": null,
        "LotType": null,
        "MaximumRentalMonthsTerm": null,
        "MediaChangeTimestamp": "2025-02-05T17:17:09.000000Z",
        "MediaListingKey": null,
        "MinimumRentalTermMonths": null,
        "MlsStatus": "New",
        "ModificationTimestamp": "2025-02-05T17:18:06.000000Z",
        "NetOperatingIncome": null,
        "NewConstructionYN": null,
        "NumberOfFullTimeEmployees": null,
        "NumberOfKitchens": null,
        "OccupantType": "Owner",
        "OfficeApartmentArea": null,
        "OfficeApartmentAreaUnit": null,
        "OriginalEntryTimestamp": "2025-02-05T17:17:09.000000Z",
        "OriginatingSystemID": "A00001796",
        "OtherExpense": null,
        "OtherStructures": [],
        "OutOfAreaMunicipality": null,
        "OutsideStorageYN": null,
        "ParcelNumber": null,
        "ParcelOfTiedLand": null,
        "ParkingFeatures": [
            "Underground"
        ],
        "ParkingLevelUnit1": "P2 (Extr Large)",
        "ParkingLevelUnit2": null,
        "ParkingMonthlyCost": null,
        "ParkingSpaces": 1,
        "ParkingSpot1": "1",
        "ParkingSpot2": null,
        "ParkingTotal": 1,
        "PercentBuilding": null,
        "PetsAllowed": [
            "Restricted"
        ],
        "PhotosChangeTimestamp": "2025-02-05T17:17:09.000000Z",
        "PoolFeatures": [],
        "PossessionDetails": "Immediate",
        "PostalCode": "M5V 0H7",
        "ProfessionalManagementExpense": null,
        "PropertyAttachedYN": true,
        "PropertyFeatures": [
            "Arts Centre",
            "Hospital",
            "Park",
            "Place Of Worship",
            "Public Transit",
            "School"
        ],
        "PropertyManagementCompany": "Goldview Property Management",
        "PropertySubType": "Condo Apartment",
        "PropertyType": "Residential Condo & Other",
        "PropertyUse": null,
        "PublicRemarks": "Experience contemporary luxury in this fully furnished 2-storey loft located in the vibrant heart of King West. This stunning space features exposed concrete ceilings, 18-foot floor-to-ceiling windows with bright west-facing sunset views, a sleek floating staircase with glass rails, and designer light fixtures throughout. Perfectly designed for modern living and entertaining in the highly sought-after Six50 King Lofts. Available for a fully furnished short-term lease (min 6 months). Ideal for professionals, executives, actors, young families, pro athletes, and more.",
        "PublicRemarksExtras": null,
        "Rail": null,
        "RentIncludes": [
            "Building Insurance",
            "Building Maintenance",
            "Central Air Conditioning",
            "Heat",
            "Cable TV",
            "High Speed Internet",
            "Parking",
            "Water"
        ],
        "RetailArea": null,
        "RetailAreaCode": null,
        "RollNumber": null,
        "Roof": [],
        "RoomsAboveGrade": 5,
        "RoomsBelowGrade": null,
        "RoomsTotal": 5,
        "RoomType": [],
        "RuralUtilities": [],
        "SeatingCapacity": null,
        "SecurityFeatures": [],
        "SeniorCommunityYN": false,
        "Sewer": [],
        "Shoreline": [],
        "ShorelineAllowance": null,
        "ShowingRequirements": [
            "Lockbox"
        ],
        "SoilTest": null,
        "SpaYN": null,
        "SpecialDesignation": [
            "Unknown"
        ],
        "SquareFootSource": "MPAC",
        "StandardStatus": "Active",
        "StateOrProvince": "ON",
        "StreetDirSuffix": null,
        "StreetName": "Bathurst",
        "StreetNumber": "95",
        "StreetSuffix": "Street",
        "StructureType": [],
        "SurveyAvailableYN": null,
        "TaxAnnualAmount": null,
        "TaxAssessedValue": null,
        "TaxType": null,
        "TaxYear": null,
        "TimestampSQL": null,
        "Topography": [],
        "TransactionType": "For Lease",
        "TruckLevelShippingDoors": null,
        "TruckLevelShippingDoorsHeightFeet": null,
        "TruckLevelShippingDoorsHeightInches": null,
        "TruckLevelShippingDoorsWidthFeet": null,
        "TruckLevelShippingDoorsWidthInches": null,
        "UFFI": null,
        "UnderContract": [],
        "UnitNumber": "424",
        "UnparsedAddress": "#424 - 95 Bathurst Street, Toronto, ON M5V 0H7",
        "Utilities": [],
        "VacancyAllowance": null,
        "VendorPropertyInfoStatement": false,
        "View": [],
        "VirtualTourURLUnbranded": null,
        "WashroomsType1": 1,
        "WashroomsType1Level": "Main",
        "WashroomsType1Pcs": 3,
        "WashroomsType2": 1,
        "WashroomsType2Level": "Second",
        "WashroomsType2Pcs": 3,
        "WashroomsType3": null,
        "WashroomsType3Level": null,
        "WashroomsType3Pcs": null,
        "WashroomsType4": null,
        "WashroomsType4Level": null,
        "WashroomsType4Pcs": null,
        "WashroomsType5": null,
        "WashroomsType5Level": null,
        "WashroomsType5Pcs": null,
        "WaterBodyName": null,
        "WaterBodyType": null,
        "WaterDeliveryFeature": [],
        "WaterExpense": null,
        "Waterfront": [],
        "WaterfrontAccessory": [],
        "WaterFrontageFt": null,
        "WaterfrontFeatures": [],
        "WaterfrontYN": false,
        "WaterSource": [],
        "WaterView": [],
        "ZoningDesignation": null,
        "updated_at": "2025-02-05T17:25:03.348000Z",
        "created_at": "2025-02-05T17:25:03.348000Z",
        "id": "67a39eef7edb9401930a6f92",
        "is_favorite": false,
        "images": [
            {
                "Order": 0,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/C11957766/thumbnail/4542c1db-192f-41f7-93ae-fbf090fa75be-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            },
            {
                "Order": 8,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/C11957766/thumbnail/1378c648-ec21-42c8-9b20-8a5e6c1e5321-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            },
            {
                "Order": 7,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/C11957766/thumbnail/d43c26cb-1a17-4597-8a32-483b2d3ad9e7-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            },
            {
                "Order": 2,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/C11957766/thumbnail/ce35d735-dfdc-44ed-801d-8c51a186d6b1-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            },
            {
                "Order": 11,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/C11957766/thumbnail/1196fcbe-c74e-4269-bb4c-2c0d9d157889-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            }
        ]
    },
    {
        "feed_type": "idx",
        "ListingKey": "X11957765",
        "AccessibilityFeatures": [],
        "AccessToProperty": [],
        "AdditionalMonthlyFee": null,
        "AdditionalMonthlyFeeFrequency": null,
        "AlternativePower": [],
        "Amps": null,
        "ApartmentNumber": null,
        "ApproximateAge": "31-50",
        "ArchitecturalStyle": [
            "2-Storey"
        ],
        "AssessmentYear": 2024,
        "AssociationAmenities": [],
        "AssociationFee": null,
        "AssociationFeeIncludes": [],
        "AssociationName": null,
        "AttachedGarageYN": false,
        "BalconyType": null,
        "Basement": [
            "Finished with Walk-Out",
            "Separate Entrance"
        ],
        "BasementYN": null,
        "BathroomsTotalInteger": 4,
        "BaySizeLengthFeet": null,
        "BaySizeLengthInches": null,
        "BaySizeWidthFeet": null,
        "BaySizeWidthInches": null,
        "BedroomsAboveGrade": 5,
        "BedroomsBelowGrade": 1,
        "BedroomsTotal": 6,
        "BoardPropertyType": "Free",
        "BuildingAreaTotal": null,
        "BuildingAreaUnits": null,
        "BuildingName": null,
        "BusinessName": null,
        "BusinessType": [],
        "CableYNA": null,
        "CentralVacuumYN": false,
        "ChannelName": null,
        "ChattelsYN": null,
        "City": "Hamilton",
        "CityRegion": "Carlisle",
        "ClearHeightFeet": null,
        "ClearHeightInches": null,
        "CommercialCondoFee": null,
        "CommercialCondoFeeFrequency": null,
        "CommonAreaUpcharge": null,
        "CommunityFeatures": [],
        "CondoCorpNumber": null,
        "ConstructionMaterials": [
            "Brick"
        ],
        "ContractStatus": "Available",
        "Cooling": [
            "Central Air"
        ],
        "CoolingYN": true,
        "Country": "CA",
        "CountyOrParish": "Hamilton",
        "CoveredSpaces": 3,
        "CraneYN": null,
        "CrossStreet": "Carlisle Road and Progreston Road",
        "DDFYN": true,
        "DenFamilyroomYN": true,
        "DevelopmentChargesPaid": [],
        "DirectionFaces": "South",
        "Disclosures": [],
        "DockingType": [],
        "DoubleManShippingDoors": null,
        "DoubleManShippingDoorsHeightFeet": null,
        "DoubleManShippingDoorsHeightInches": null,
        "DoubleManShippingDoorsWidthFeet": null,
        "DoubleManShippingDoorsWidthInches": null,
        "DriveInLevelShippingDoors": null,
        "DriveInLevelShippingDoorsHeightFeet": null,
        "DriveInLevelShippingDoorsHeightInches": null,
        "DriveInLevelShippingDoorsWidthFeet": null,
        "DriveInLevelShippingDoorsWidthInches": null,
        "ElectricExpense": null,
        "ElectricOnPropertyYN": null,
        "ElectricYNA": null,
        "ElevatorType": null,
        "ElevatorYN": false,
        "EnsuiteLaundryYN": false,
        "EstimatedInventoryValueAtCost": null,
        "Expenses": null,
        "Exposure": null,
        "ExteriorFeatures": [],
        "FarmType": null,
        "FinancialStatementAvailableYN": null,
        "FireplaceFeatures": [
            "Natural Gas",
            "Family Room"
        ],
        "FireplaceYN": true,
        "FoundationDetails": [
            "Poured Concrete"
        ],
        "FranchiseYN": null,
        "FreestandingYN": null,
        "FrontageLength": null,
        "Furnished": null,
        "GarageParkingSpaces": null,
        "GarageType": "Attached",
        "GarageYN": true,
        "GradeLevelShippingDoors": null,
        "GradeLevelShippingDoorsHeightFeet": null,
        "GradeLevelShippingDoorsHeightInches": null,
        "GradeLevelShippingDoorsWidthFeet": null,
        "GradeLevelShippingDoorsWidthInches": null,
        "HeatingExpenses": null,
        "HeatingYN": true,
        "HeatSource": "Gas",
        "HeatType": "Forced Air",
        "HoursDaysOfOperation": [],
        "HoursDaysOfOperationDescription": null,
        "HSTApplication": true,
        "IndustrialArea": null,
        "IndustrialAreaCode": null,
        "InsuranceExpense": null,
        "InteriorFeatures": [
            "Auto Garage Door Remote",
            "In-Law Suite",
            "Primary Bedroom - Main Floor",
            "Carpet Free"
        ],
        "InternetAddressDisplayYN": true,
        "InternetEntireListingDisplayYN": true,
        "KitchensAboveGrade": 2,
        "KitchensBelowGrade": null,
        "KitchensTotal": 2,
        "LaundryFeatures": [],
        "LeasedTerms": null,
        "LeaseToOwnEquipment": [],
        "LegalStories": null,
        "LinkProperty": null,
        "LinkYN": false,
        "ListOfficeKey": "079817",
        "ListOfficeName": "RE/MAX REAL ESTATE CENTRE INC.",
        "ListPrice": 2499000,
        "ListPriceUnit": null,
        "LivingAreaRange": "3000-3500",
        "Locker": null,
        "LockerLevel": null,
        "LockerNumber": null,
        "LockerUnit": null,
        "LotDepth": 200.48,
        "LotDimensionsSource": "Other",
        "LotFeatures": [
            "Irregular Lot"
        ],
        "LotIrregularities": "259.18 X 249.78 X 200.48 X320.56 X 91.08",
        "LotShape": "Rectangular",
        "LotSizeRangeAcres": ".50-1.99",
        "LotSizeSource": "Other",
        "LotSizeUnits": "Feet",
        "LotType": null,
        "MaximumRentalMonthsTerm": null,
        "MediaChangeTimestamp": "2025-02-05T17:16:22.000000Z",
        "MediaListingKey": null,
        "MinimumRentalTermMonths": null,
        "MlsStatus": "New",
        "ModificationTimestamp": "2025-02-05T17:16:22.000000Z",
        "NetOperatingIncome": null,
        "NewConstructionYN": null,
        "NumberOfFullTimeEmployees": null,
        "NumberOfKitchens": null,
        "OccupantType": "Owner",
        "OfficeApartmentArea": null,
        "OfficeApartmentAreaUnit": null,
        "OriginalEntryTimestamp": "2025-02-05T17:16:21.000000Z",
        "OriginatingSystemID": "A00001796",
        "OtherExpense": null,
        "OtherStructures": [
            "Garden Shed"
        ],
        "OutOfAreaMunicipality": null,
        "OutsideStorageYN": null,
        "ParcelNumber": "175210008",
        "ParcelOfTiedLand": "No",
        "ParkingFeatures": [
            "Circular Drive"
        ],
        "ParkingLevelUnit1": null,
        "ParkingLevelUnit2": null,
        "ParkingMonthlyCost": null,
        "ParkingSpaces": 10,
        "ParkingSpot1": null,
        "ParkingSpot2": null,
        "ParkingTotal": 12,
        "PercentBuilding": null,
        "PetsAllowed": [],
        "PhotosChangeTimestamp": "2025-02-05T17:16:22.000000Z",
        "PoolFeatures": [
            "Inground"
        ],
        "PossessionDetails": "60-90 Days",
        "PostalCode": "L0R 1H3",
        "ProfessionalManagementExpense": null,
        "PropertyAttachedYN": null,
        "PropertyFeatures": [
            "Campground",
            "Cul de Sac/Dead End",
            "Golf",
            "Greenbelt/Conservation",
            "Park",
            "Ravine"
        ],
        "PropertyManagementCompany": null,
        "PropertySubType": "Detached",
        "PropertyType": "Residential Freehold",
        "PropertyUse": null,
        "PublicRemarks": "Stunning Custom Home On Private Approx. 2 Acre Lot On A Quiet Court In Highly Desirable Carlisle. Fantastic Curb Appreal !! Enjoy Wildlife and Tranquility Of The Large Green Space. Meticulously Cared For, This Sun-Filled 3,200 Sq.Ft, 5+2 Beds, 4 Baths Home. Fully Renovated New Basement In-Law Suite. A Circular Driveway (Can Fit 10+ Cars) & Beautiful Perennial Gardens At Entrance, 3 Garages (Oversized Attached 2 Car Garage & Detached 1 Garage). Main Floor Bedroom & Laundry With Access to the Garage. Main Floor Features Hardwood Floorings In The Formal Living, Dining & Family Rooms. Great Views in Every Room. Gorgeous Newly Renovated Whitish Open Concept Eat-In Kitchen with Island, Quartz Countertops, Backsplash, Marble Floor, SS Appliance & Lights. Updated 2nd Floor Main Bath and Main floor 3 Pcs Bath. 2nd Floor Large Master Suite and A Bonus Studio/Office. Completely New Walk-out Basement In-Law Suite with Separate Entrance Contains Kitchen, Bedroom with 3 Pcs Ensuite & Walk-in Closet, Office, Living/Dining Room, Fire place. Less Than 10 Years for All Windows, Furnace/A/C and Roof Shingle, Fenced In-Ground Pool & New equipment (Sand Filter System/Pool Liner/Pool Cover/Pump-2023), Garden Shed.. THE MOST PITCTURESQUE SETTING. Truly A Gem!!Call For a private Showing.",
        "PublicRemarksExtras": null,
        "Rail": null,
        "RentIncludes": [],
        "RetailArea": null,
        "RetailAreaCode": null,
        "RollNumber": "251830381004030",
        "Roof": [
            "Asphalt Shingle"
        ],
        "RoomsAboveGrade": 13,
        "RoomsBelowGrade": null,
        "RoomsTotal": 10,
        "RoomType": [],
        "RuralUtilities": [],
        "SeatingCapacity": null,
        "SecurityFeatures": [],
        "SeniorCommunityYN": null,
        "Sewer": [
            "Septic"
        ],
        "Shoreline": [],
        "ShorelineAllowance": null,
        "ShowingRequirements": [
            "Showing System"
        ],
        "SoilTest": null,
        "SpaYN": null,
        "SpecialDesignation": [
            "Unknown"
        ],
        "SquareFootSource": null,
        "StandardStatus": "Active",
        "StateOrProvince": "ON",
        "StreetDirSuffix": null,
        "StreetName": "Iris",
        "StreetNumber": "6",
        "StreetSuffix": "Court",
        "StructureType": [],
        "SurveyAvailableYN": null,
        "TaxAnnualAmount": 8948.37,
        "TaxAssessedValue": 788000,
        "TaxType": null,
        "TaxYear": 2024,
        "TimestampSQL": null,
        "Topography": [],
        "TransactionType": "For Sale",
        "TruckLevelShippingDoors": null,
        "TruckLevelShippingDoorsHeightFeet": null,
        "TruckLevelShippingDoorsHeightInches": null,
        "TruckLevelShippingDoorsWidthFeet": null,
        "TruckLevelShippingDoorsWidthInches": null,
        "UFFI": true,
        "UnderContract": [],
        "UnitNumber": null,
        "UnparsedAddress": "6 Iris Court, Hamilton, ON L0R 1H3",
        "Utilities": [],
        "VacancyAllowance": null,
        "VendorPropertyInfoStatement": false,
        "View": [
            "Forest",
            "Hills",
            "Trees/Woods"
        ],
        "VirtualTourURLUnbranded": "https://viralrealestate.media/6-iris-court-1",
        "WashroomsType1": 1,
        "WashroomsType1Level": "Main",
        "WashroomsType1Pcs": 3,
        "WashroomsType2": 2,
        "WashroomsType2Level": "Second",
        "WashroomsType2Pcs": 4,
        "WashroomsType3": 1,
        "WashroomsType3Level": "Basement",
        "WashroomsType3Pcs": 3,
        "WashroomsType4": null,
        "WashroomsType4Level": null,
        "WashroomsType4Pcs": null,
        "WashroomsType5": null,
        "WashroomsType5Level": null,
        "WashroomsType5Pcs": null,
        "WaterBodyName": null,
        "WaterBodyType": null,
        "WaterDeliveryFeature": [],
        "WaterExpense": null,
        "Waterfront": [],
        "WaterfrontAccessory": [],
        "WaterFrontageFt": null,
        "WaterfrontFeatures": [],
        "WaterfrontYN": false,
        "WaterSource": [
            "Drilled Well"
        ],
        "WaterView": [],
        "ZoningDesignation": null,
        "updated_at": "2025-02-05T17:20:04.566000Z",
        "created_at": "2025-02-05T17:20:04.566000Z",
        "id": "67a39dc47daf956a910ba8b4",
        "is_favorite": false,
        "images": [
            {
                "Order": 7,
                "image_url": "https://s3.ca-central-1.amazonaws.com/mls-trreb/properties/X11957765/thumbnail/b62b1939-0abd-49dd-aa17-1d40035d4247-t.jpg",
                "ImageSizeDescription": "Thumbnail"
            }
        ]
    }
] 
const propertyData = data.length > 0 ? data.map((data: HomeDataRes) => ({
      title: data.CityRegion ?? data.City ?? "",
      sqft: data.LivingAreaRange ?? 0,
      beds: data.BedroomsTotal ?? 0,
      baths: data.BathroomsTotalInteger ?? 0,
      images: data.images?.length > 0 ? data.images.map((image: { order: number; image_url: string}) => image.image_url) : [],
      address: data.UnparsedAddress,
      price: (data.ListPrice ?? 0).toLocaleString("en-US"),
      listingKey: data.ListingKey,
      transactionType: data.TransactionType ?? "",
      isFavorite: data.is_favorite ?? false,
    })) : []
    return propertyData;
}

interface Props {
  recent?: boolean;
}

const HomesCarousel = ({ recent }: Props) => {
  const properties = useQuery({
    queryKey: ["excludedQueryKey", "properties", recent],
    queryFn: () => fetchProperties(recent),
    staleTime: 1000 * 60 * 5,
  })

  return (
    <div className={styles.carouselSection}>
      <div className={styles.carouselContainer}>
        <Heading title="Recent Properties" description="Based on your view history" />
        {/* <Swiper
          key={properties.data?.length}
          modules={[Navigation]}
          spaceBetween={30}
          slidesPerView={4}
          navigation
          observer={true}
	        observeParents={true}
        > */}
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2 md:gap-3 lg:gap-4">
          {properties?.isLoading ?
            <>
              <HomeCardSkeleton />
              <HomeCardSkeleton />
              <HomeCardSkeleton />
              <HomeCardSkeleton />
            </>
          : (properties.data?.length > 0 && properties.data.map((home: HomeData) => (
            <SwiperSlide key={home.listingKey}>
              <HomeDetailCard {...home} />
            </SwiperSlide>
          )))}
        </div>
        {/* </Swiper> */}
        <div className="flex justify-center mt-[50px]">
          <Button as={Link} className="text-base font-medium shadow-sm py-2\.5 px-8 rounded-full !text-white bg-gray-900" href="/property">View All</Button>
        </div>
      </div>
    </div>
  );
};

export default HomesCarousel;